### PR TITLE
Fix `npm install` to new `npm ci` for faster CI builds

### PR DESCRIPTION
**Pull request by vladdoster**
ref #13

### CODE REVIEW

**Comment by vladdoster** [comment]
Well @benceHornyak I think you are right about npm version.

**Comment by benceHornyak** [comment]
I think I was wrong actually. Checked npm version in the logs.. 6.5.0-next is more than enough. npm ci doesn't seem to be supported be default. May be you can try as a custom command

**Comment by vladdoster** [comment]
I will try that

@Ethan-Arrowood see anything that would make you opposed t o a custom command or am I missing something?

**Comment by Ethan-Arrowood** [comment]
Ahh yes you need to use a custom command similar to that of `lint`. Please also change the task displayName to reflect `ci` instead of `install`

**Comment by Ethan-Arrowood** [comment]
Why do you keep opening and closing PRs on the same branch? If you have any questions make sure to reach out I’m happy to help

**Pull request closed without merging**
